client_1:
  model:
    type: convnet2
    hidden: 512
    out_channels: 62
    dropout: 0.0
  criterion:
    type: CrossEntropyLoss
  train:
    local_update_steps: 1
    batch_or_epoch: epoch
    optimizer:
      type: SGD
      lr: 0.01
      weight_decay: 0.0
      momentum: 0.5
client_2:
  model:
    type: convnet2
    hidden: 64
    out_channels: 62
    dropout: 0.0
  criterion:
    type: CrossEntropyLoss
  train:
    local_update_steps: 1
    batch_or_epoch: epoch
    optimizer:
      type: SGD
      lr: 0.01
      weight_decay: 0.0
      momentum: 0.5
client_3:
  model:
    type: convnet2
    hidden: 128
    out_channels: 62
    dropout: 0.0
  criterion:
    type: CrossEntropyLoss
  train:
    local_update_steps: 1
    batch_or_epoch: epoch
    optimizer:
      type: SGD
      lr: 0.01
      weight_decay: 0.0
      momentum: 0.5
client_4:
  model:
    type: convnet2
    hidden: 256
    out_channels: 62
    dropout: 0.0
  criterion:
    type: CrossEntropyLoss
  train:
    local_update_steps: 1
    batch_or_epoch: epoch
    optimizer:
      type: SGD
      lr: 0.01
      weight_decay: 0.0
      momentum: 0.5
client_5:
  model:
    type: convnet2
    hidden: 512
    out_channels: 62
    dropout: 0.0
  criterion:
    type: CrossEntropyLoss
  train:
    local_update_steps: 1
    batch_or_epoch: epoch
    optimizer:
      type: SGD
      lr: 0.01
      weight_decay: 0.0
      momentum: 0.5
