use_gpu: True
device: 0
early_stop:
  patience: 5
seed: 12345
check_completeness: True
federate:
  mode: standalone
  method: fedhenn
  client_num: 2
  total_round_num: 110
  sample_client_rate: 1.0
  make_global_eval: False
data:
  root: data/
  type: 'CIFAR10@torchvision'
  splits: [1.0, 0.0, 0.0]
  num_workers: 0
  transform: [['ToTensor'], ['Normalize', {'mean': [0.485, 0.456, 0.406], 'std': [0.229, 0.224, 0.225]}]]
  test_transform: [['ToTensor'], ['Normalize', {'mean': [0.485, 0.456, 0.406], 'std': [0.229, 0.224, 0.225]}]]
  args: [{'download': True}]
  splitter: 'lda'
  splitter_args: [{'alpha': 0.05}]
dataloader:
  batch_size: 64
train:
  local_update_steps: 1
  batch_or_epoch: epoch
  optimizer:
    type: SGD
    lr: 0.01
    weight_decay: 0.0
    momentum: 0.5
criterion:
  type: CrossEntropyLoss
trainer:
  type: fedhenn_trainer
eval:
  freq: 1
  metrics: ['acc', 'correct']
  best_res_update_round_wise_key: test_loss

