use_gpu: True
device: 0
early_stop:
  patience: 5
seed: 1234
federate:
  mode: standalone
  method: fedproto
  client_num: 20
  total_round_num: 110
  sample_client_rate: 1.0
  make_global_eval: False
data:
  root: data/
  type: femnist
  splits: [ 0.6,0.2,0.2 ]
  subsample: 0.05
  transform: [ [ 'ToTensor' ], [ 'Normalize', { 'mean': [ 0.9637 ], 'std': [ 0.1592 ] } ] ]
dataloader:
  batch_size: 4
train:
  local_update_steps: 1
  batch_or_epoch: epoch
  optimizer:
    type: SGD
    lr: 0.01
    weight_decay: 0.0
    momentum: 0.5
criterion:
  type: CrossEntropyLoss
trainer:
  type: fedproto_trainer
eval:
  freq: 1
  metrics: ['acc', 'correct']
  best_res_update_round_wise_key: test_loss

