client_1:
  model:
    type: shufflenetv2_proto
    out_channels: 10
    dropout: 0.0
client_2:
  model:
    type: resnet18_proto
    out_channels: 10
    dropout: 0.0
  criterion:
    type: CrossEntropyLoss
client_3:
  model:
    type: CNN_proto
    out_channels: 10
    dropout: 0.0
    hidden: 512
client_4:
  model:
    type: cct_proto
    out_channels: 10
  train:
    optimizer:
      type: Adam
      lr: 6e-4
      weight_decay: 6e-2
client_5:
  model:
    type: MLP_proto
    out_channels: 10
    hidden: 512
    layer: 4
    dropout: 0.0