use_gpu: True
device: 0
early_stop:
  patience: 10
seed: 12345
federate:
  method: fsfl
  mode: standalone
  sample_client_rate: 1.0
  client_num: 2
  make_global_eval: False
data:
  root: data/
  type: femnist
  splits: [ 0.6,0.2,0.2 ]
  subsample: 0.05
  transform: [ [ 'ToTensor' ], [ 'Normalize', { 'mean': [ 0.9637 ], 'std': [ 0.1592 ] } ] ]
dataloader:
  batch_size: 5 #according to soure code of the paper
train:
  local_update_steps: 1
  batch_or_epoch: epoch
  optimizer:
    type: Adam
    lr: 0.001
    weight_decay: 1e-4
criterion:
  type: CrossEntropyLoss
eval:
  freq: 1
  metrics: ['acc', 'correct']
MHFL:
  task: CV
  save_pretraining_model: True
  save_model: True
  public_dataset: mnist
  public_train:
    batch_size: 127
    optimizer:
      type: Adam
      lr: 0.01
      weight_decay: 0.0
fsfl:
  pre_training_epochs: 1
  domain_identifier_epochs: 4
  gan_local_epochs: 4
  collaborative_epoch: 1
  collaborative_num_samples_epochs: 5000
  MAFL_batch_size: 256
  DI_optimizer:
    type: Adam
    lr: 0.001
    weight_decay: 1e-4
  DI_optimizer_step_2:
    type: Adam
    lr: 0.0001
    weight_decay: 1e-4
finetune:
  before_eval: True
  local_update_steps: 1
  optimizer:
    type: Adam
    lr: 0.001