client_1:
  model:
    type: CNN_2layers
    out_channels: 100
    dropout: 0.2
    hidden: 256
    filter_channels: [128,256]
  train:
    optimizer:
      type: Adam
      lr: 0.001
      weight_decay: 0.
client_2:
  model:
    type: CNN_3layers
    out_channels: 100
    dropout: 0.2
    hidden: 256
    filter_channels: [128,128,192]
  train:
    optimizer:
      type: Adam
      lr: 0.001
      weight_decay: 0.
client_3:
  model:
    type: CNN_3layers
    out_channels: 100
    dropout: 0.2
    hidden: 256
    filter_channels: [64,64,64]
  train:
    optimizer:
      type: Adam
      lr: 0.001
      weight_decay: 0.
client_4:
  model:
    type: CNN_3layers
    out_channels: 100
    dropout: 0.3
    hidden: 256
    filter_channels: [128,64,64]
  train:
    optimizer:
      type: Adam
      lr: 0.001
      weight_decay: 0.
client_5:
  model:
    type: CNN_3layers
    out_channels: 100
    dropout: 0.4
    hidden: 256
    filter_channels: [64,64,128]
  train:
    optimizer:
      type: Adam
      lr: 0.001
      weight_decay: 0.
client_6:
  model:
    type: CNN_3layers
    out_channels: 100
    dropout: 0.2
    hidden: 256
    filter_channels: [64,128,256]
  train:
    optimizer:
      type: Adam
      lr: 0.001
      weight_decay: 0.
client_7:
  model:
    type: CNN_3layers
    out_channels: 100
    dropout: 0.2
    hidden: 256
    filter_channels: [64,128,192]
  train:
    optimizer:
      type: Adam
      lr: 0.001
      weight_decay: 0.
client_8:
  model:
    type: CNN_3layers
    out_channels: 100
    dropout: 0.2
    hidden: 256
    filter_channels: [128,192,256]
  train:
    optimizer:
      type: Adam
      lr: 0.001
      weight_decay: 0.
client_9:
  model:
    type: CNN_3layers
    out_channels: 100
    dropout: 0.3
    hidden: 256
    filter_channels: [128,128,128]
  train:
    optimizer:
      type: Adam
      lr: 0.001
      weight_decay: 0.
client_10:
  model:
    type: CNN_4layers
    out_channels: 100
    dropout: 0.2
    hidden: 256
    filter_channels: [64,64,64,64]
  train:
    optimizer:
      type: Adam
      lr: 0.001
      weight_decay: 0.
